on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish
        id: hello
        # with:
        #   who-to-greet: "World"
        with:
          github-object: ${{ toJson(github)}}
      - run: |
          echo "${{ steps.hello.outputs.mergeMessage }}"

# name: Actions Workflow

# on: [push]

# jobs:
#   run-github-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: List Files
#         run: |
#           pwd
#           ls
#       - name: Simple JS Actions
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: John
#       - name: Log Greeting Time
#         run: echo "${{ steps.greet.outputs.time }}"
