name: Merge Check

on:
  push:
    branches:
      - master
      # - STUDIO-439
  # pull_request:
  #   branches:
  #     - master
  #   types:
  #     - ready_for_review
  #     - review_requested
  #     - opened

jobs:
  checkForMerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish
        id: merge
      - run: |
          echo "${{ steps.merge.outputs.mergeMessage }}"
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            put
            users 
            here
      - run: |
          echo ${{ steps.issue.outputs.issue }}
        # with:
        #   github-object: ${{ toJson(github.event)}}
        #   committer-username: ${{ toJson(github.event.commits[github.event.commits.length-1])}}
        # github-object: ${{ toJson(github.event.commits[github.event.commits-1].message)}}


# name: Actions Workflow

# on: [push]

# jobs:
#   run-github-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: List Files
#         run: |
#           pwd
#           ls
#       - name: Simple JS Actions
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: John
#       - name: Log Greeting Time
#         run: echo "${{ steps.greet.outputs.time }}"
