name: Merge & Publish

on:
  push:
    branches:
      - master
      - STUDIO-439
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested
      - opened

jobs:
  checkForMerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish
      - name: Github Event Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_MESSAGE: ${{ toJson(github.event.commits[github.event.commits-1].message)}}
        id: merge
        # with:
        #   who-to-greet: "World"
        with:
          # github-object: ${{ toJson(github)}}
          github-object: "$GITHUB_MESSAGE"
      - run: |
          echo "${{ steps.merge.outputs.mergeMessage }}"

# name: Actions Workflow

# on: [push]

# jobs:
#   run-github-actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: List Files
#         run: |
#           pwd
#           ls
#       - name: Simple JS Actions
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: John
#       - name: Log Greeting Time
#         run: echo "${{ steps.greet.outputs.time }}"
